### ISSUE TITLE
Adding a new rule raises an exception

### ISSUE THREAD

**Issue by orientalperil** [boxed/Waker#1]
I downloaded Waker.app.zip, launched the app, and when I tried to add a new rule it throws an exception: (AttributeError: 'NoneType' object has no attribute 'hide_').

**Comment by boxed** [comment]
Wow, I can't believe I didn't comment on this issue way back in 2011. Embarrassing! Anyway, I have since then rewritten it all in objective-c (2013), not done anything since then, then now dusted it off again and fixed it after it broke badly. The new version I'm working on for my personal use drops itunes connectivity because it doesn't work anyway, and instead looks for music (mp3 and m4a) in `~/Music/Waker/`, then `~/Music/` and finally falls back to the backup song.

I'm gonna try it live for the first time tomorrow, let's see how it goes! But this issue is most definitely obsolete :)
